---
abstract: 'Processing PYX data or file and print histogram.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  Capture::Tiny: 0
  English: 0
  Error::Pure::Utils: 0.22
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.07
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PYX-Hist
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Class::Utils: 0.05
  Error::Pure: 0.16
  List::Util: 1.41
  PYX::Parser: 0.02
  perl: 5.6.0
resources:
  bugtracker: https://github.com/michal-josef-spacek/PYX-Hist/issues
  homepage: https://github.com/michal-josef-spacek/PYX-Hist
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/PYX-Hist
version: '0.07'
